# Generated by Django 2.1.5 on 2020-03-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddata',
            name='link',
        ),
        migrations.RemoveField(
            model_name='boarddata',
            name='specific_id',
        ),
    ]
